#!/usr/bin/env python
import argparse
from molconvert import main
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('from_mol')
    parser.add_argument('to_mol')
    pargs = parser.parse_args()
    # defalt
    main(
        pargs.from_mol, pargs.to_mol, 
        )
       
